task_name: train
tags:
- real_focus
- mobilenetv3
train: true
test: true
ckpt_path: /home/maf4031/focus_model/logs/wandb_sweep/runs/2022-12-31_18-16-15/checkpoints/epoch_086.ckpt
seed: 12345
datamodule:
  _target_: src.datamodules.focus_datamodule.FocusDataModule
  data_dir: ${paths.data_dir}
  batch_size: 64
  splits:
  - 0.8
  - 0.1
  num_workers: 20
  pin_memory: false
  subsample: true
  subsample_size: 100
model:
  _target_: src.models.focus_module.FocusModule
  optimizer:
    _target_: torch.optim.Adam
    _partial_: true
    lr: 9.166172272883112e-05
    weight_decay: 0.03871610561432232
  net:
    _target_: src.models.components.mobile_net_v3.MobileNetV3
    transfer: false
callbacks:
  model_checkpoint:
    _target_: pytorch_lightning.callbacks.ModelCheckpoint
    dirpath: ${paths.output_dir}/checkpoints
    filename: epoch_{epoch:03d}
    monitor: val/focus_error
    verbose: false
    save_last: true
    save_top_k: 1
    mode: min
    auto_insert_metric_name: false
    save_weights_only: false
    every_n_train_steps: null
    train_time_interval: null
    every_n_epochs: null
    save_on_train_epoch_end: null
  early_stopping:
    _target_: pytorch_lightning.callbacks.EarlyStopping
    monitor: val/loss
    min_delta: 0.0
    patience: 100
    verbose: false
    mode: min
    strict: true
    check_finite: true
    stopping_threshold: null
    divergence_threshold: null
    check_on_train_epoch_end: null
  model_summary:
    _target_: pytorch_lightning.callbacks.RichModelSummary
    max_depth: -1
  rich_progress_bar:
    _target_: pytorch_lightning.callbacks.RichProgressBar
logger:
  wandb:
    _target_: pytorch_lightning.loggers.wandb.WandbLogger
    save_dir: ${paths.output_dir}
    offline: false
    id: fhk87q98
    anonymous: null
    project: FocusNewData
    log_model: false
    prefix: ''
    group: focus
    tags: ${tags}
    job_type: ''
trainer:
  _target_: pytorch_lightning.Trainer
  default_root_dir: ${paths.output_dir}
  min_epochs: 1
  max_epochs: 50
  accelerator: gpu
  devices: 1
  precision: 16
  check_val_every_n_epoch: 1
  deterministic: false
  gradient_clip_val: 0
paths:
  root_dir: ${oc.env:PROJECT_ROOT}
  data_dir: /n/data2/hms/dbmi/kyu/lab/maf4031/focus_dataset/
  log_dir: ${paths.root_dir}/logs/
  output_dir: ${hydra:runtime.output_dir}
  work_dir: ${hydra:runtime.cwd}
extras:
  ignore_warnings: false
  enforce_tags: true
  print_config: true
