# TODOs before submitting a sweep
# 1. Is all code committed?
#   --> create new sweep branch to run from!
# 2. Was the code tested? 
# 3. Check if all default values make sense/are desired
# 4. Is the run correctly specified?
#    --> project 
#    --> name
#    --> tags
#    --> task name (DON'T change, only for specific reasons)
# 5. Loading correct dataset?
# 6. Check optimal number of workers for dataset
# --> Let's go!
description: Sweep on on subset of whole training data

program: src/train.py
project: SweepFocusModelResize
name: SweepFocusModelComplete
method: bayes
metric:
  name: val/loss
  goal: minimize
parameters:
  task_name: 
    value: wandb_sweep
  trainer.accelerator:
    value: gpu
  trainer.devices:
    value: 1
  trainer.max_epochs:
    value: 100
  #trainer.gradient_clip_val:
  #  value: 0.5
  model.optimizer.lr:
    min: 0.00001
    max: 0.0001
  model.optimizer.weight_decay:
    min: 0.02
    max: 0.05
  model.net.transfer:
    value: False
  datamodule.batch_size:
    values: [32]
  datamodule.subsample: 
    value: True
  datamodule.subsample_size: 
    value: 100
  datamodule.num_workers:
    value: 8
  datamodule.select_patches_grid:
    value: False
  datamodule.transformations.params.resize_img:
    value: True
  callbacks.early_stopping.patience:
    value: 20
  datamodule.dataset_dir:
    value: /home/maf4031/focus_model/data/datasets/dataset_subsample100_complete.pt
  paths.data_dir:
    value: /n/data2/hms/dbmi/kyu/lab/maf4031/focus_dataset/

command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}