program: src/train.py
project: Test
name: transfer_sweep
method: bayes
metric:
  name: val/loss
  goal: minimize
parameters:
  trainer.accelerator:
    value: gpu
  trainer.devices:
    value: 1
  trainer.max_epochs:
    value: 150
  #trainer.gradient_clip_val:
  #  value: 0.5
  model.optimizer.lr:
    min: 0.00001
    max: 0.001
  model.optimizer.weight_decay:
    min: 0.04
    max: 0.05
  datamodule.batch_size:
    values: [8, 16, 32]
  datamodule.subsample: 
    value: True
  datamodule.subsample_size: 
    value: 100
  datamodule.num_workers:
    value: 8
  model.net.transfer:
    value: True
  paths.data_dir:
    value: /n/data2/hms/dbmi/kyu/lab/maf4031/focus_dataset/

command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}