program: src/train.py
name: test123
method: bayes
metric:
  name: val/loss
  goal: minimize
parameters:
  model.optimizer.lr:
    min: 0.00001
    max: 0.001
  model.optimizer.weight_decay:
    min: 0.01
    max: 0.05
  datamodule.batch_size:
    values: [1, 8]

command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}