_target_: src.datamodules.focus_datamodule.FocusDataModule
data_dir: ${paths.data_dir}
batch_size: 1
splits: [0.8, 0.1]
num_workers: 0
pin_memory: False
subsample: False
subsample_size: 50
select_patches_grid: False
select_patches_random: False
